package com.example.danson.navigation

const val ROUT_HOME = "home"
const val ROUT_LOGIN = "login"
const val ROUT_SIGNUP = "signup"
const val ROUT_UPLOAD = "upload"
const val ROUT_DASHBOARD = "dashboard"
const val ROUT_ABOUT = "about"
const val ROUT_CONTACT = "contact"
const val ROUT_SPLASH = "splash"
const val ROUT_SERVICES = "services"
const val ROUT_CLOTHING = "clothing"
const val ROUT_MALINDI = "malindi"
const val ROUT_NAKURU  = "nakuru"
const val ROUT_KISUMU  = "kisumu"
const val ROUT_MOMBASA = "mombasa"
const val ROUT_NAIVASHA = "naivasha"